### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by bestlem** [ToyVo/nh#1]
How do you install this.

The README documentation shows the instructions from @ViperML's original.

Your fork is obviously not in nixpkgs as the name would conflict.

Also does the fork work with the Nix-Darwin PR https://github.com/LnL7/nix-darwin/pull/942

**Comment by bestlem** [comment]
A possible name would be nh-darwin.
So shows it is a version of nh and also what is special about it.

We are not on slow teletypes or 120baud serial lines so don't need short names.

**Comment by bestlem** [comment]
I have been running with the nix run with no problems.

I just tried using your Nix-Darwin patch.
nh --version should return something showing it is the darwin version.
Shouldn't you darwin patch set program.nk.package to your version or does that immediately for Nix-Darwin to include your repo in flake inputs (or does nix lazily evaluate enough?)

**Comment by ToyVo** [comment]
I just rebased on upstream and I updated the version to add that darwin suffix you requested so you can easily tell if you are using this fork

**Comment by ToyVo** [comment]
I have now renamed to nh-darwin. I have not added a module option to add an alias, you'll have to do that yourself. Additionally the default darwin module is now designed for after the nix-darwin PR is merged, for before hand if you want my version of the module you can use prebuiltin module instead of the default one

```nix
{ inputs, ... }: {
  imports = [
    inputs.nh.nixDarwinModules.prebuiltin
   ];

  config = {
    programs.nh.enable = true;
  };
}
```
